name: idesk_chat_sdk_flutter
description: "Flutter package of idesk chat sdk."
authors:
  - Abdur Rahman Rahat<rahat.codeware@gmail.com>

version: 0.0.1
homepage: https://github.com/rahatfci/idesk_chat_sdk_flutter.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: 5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
